In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------------ --------------------------- 3.9/12.6 MB 18.9 MB/s eta 0:00:01
   -------------------- ------------------- 6.6/12.6 MB 15.6 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 14.6 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 13.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 7.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [4]:
import numpy as np

In [8]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

arr = np.random.randint(1, 100, size=(3,3))
print (arr)  

arr2 = arr.T 
print (arr2)

[[77 40 99]
 [ 1 65 19]
 [28 13 23]]
[[77  1 28]
 [40 65 13]
 [99 19 23]]


In [18]:
#2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array. 
b=[1, 10 ,15 ,6 ,45 ,43,18, 9 ,13, 20]
#array with 10 elements 
a= np.array(b)
print (a)
#reshaping array into 2x5
a1=a.reshape(2,5)
print(a1)
#reshaping array into 5x2
a2=a1.reshape(5,2)
print(a2)

[ 1 10 15  6 45 43 18  9 13 20]
[[ 1 10 15  6 45]
 [43 18  9 13 20]]
[[ 1 10]
 [15  6]
 [45 43]
 [18  9]
 [13 20]]


In [7]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array. 

d= np.random.rand(4,4)  
print(d)

arrborder = np.zeros((6, 6))

arrborder[1:5, 1:5] = d 

print(arrborder)


[[0.71784135 0.06309173 0.37518199 0.21659226]
 [0.10442114 0.43164642 0.44201518 0.24944832]
 [0.28117255 0.87152404 0.36314809 0.4122412 ]
 [0.01649612 0.36705478 0.95080255 0.88998766]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.71784135 0.06309173 0.37518199 0.21659226 0.        ]
 [0.         0.10442114 0.43164642 0.44201518 0.24944832 0.        ]
 [0.         0.28117255 0.87152404 0.36314809 0.4122412  0.        ]
 [0.         0.01649612 0.36705478 0.95080255 0.88998766 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

y=np.arange(10,60,5)
print(y)

[10 15 20 25 30 35 40 45 50 55]


In [37]:
 #5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element. 

arr=np.array(['python', 'numpy', 'pandas']) 
print(arr)
#uppercase
uarr=np.char.upper(arr)
print(uarr) 
#lowercase
larr=np.char.lower(arr)
print(larr)
#title
tarr=np.char.title(arr)
print(tarr)
#capitalize
carr=np.char.capitalize(arr)
print(carr)

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']
['Python' 'Numpy' 'Pandas']


In [44]:
 #6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

warr= np.array(['Bijay' ,'ajay' ,'python', 'sanjay'])
print(warr) 

sarr= np.char.join(' ', warr)
print(sarr)


['Bijay' 'ajay' 'python' 'sanjay']
['B i j a y' 'a j a y' 'p y t h o n' 's a n j a y']


In [45]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

array1 = np.array([[20, 28, 36], [40, 50, 80]])
array2 = np.array([[13, 8, 6], [10, 15, 21]])

add=array1+array2 
print(add) 

sub=array1-array2 
print(sub)

mul=array1*array2 
print(mul)

divi=array1/array2 
print(divi)

[[ 33  36  42]
 [ 50  65 101]]
[[ 7 20 30]
 [30 35 59]]
[[ 260  224  216]
 [ 400  750 1680]]
[[1.53846154 3.5        6.        ]
 [4.         3.33333333 3.80952381]]


In [50]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements. n

im=np.identity(5)       
print(im)

id=im.diagonal()       #here i used .diagnol to extract diagnol elements 
print(id)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [58]:
#9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

iarr=np.random.randint(0,1000 , size=100)
print(iarr) 

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if (n % i) == 0:
             return False
 
    return True 

    
prime_no= [num for num in iarr if is_prime(num)]

print(prime_no)


[ 88 237 661 111 714 719 598 471 667 683 861 973 971  67 235  25 258 109
 455 784 659 581 934 747   9 611 116 904 115 134 995  14 928 540 435  68
 786 233 609  19 290 834 407 838 183 361  63 382 581 721 153 115  66 831
 491 437 303 859 168 646 171 885 766 189 162 530 720 937 633 218 311 778
 452 542 370 981 948 620 522 109 111 901 371 495 619  60 790 852 252 900
 280 173 829 454  17 975 130 639 279 824]
[np.int32(661), np.int32(719), np.int32(683), np.int32(971), np.int32(67), np.int32(109), np.int32(659), np.int32(233), np.int32(19), np.int32(491), np.int32(859), np.int32(937), np.int32(311), np.int32(109), np.int32(619), np.int32(173), np.int32(829), np.int32(17)]


In [62]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.


# Creating a NumPy array representing daily temperature
dt= np.random.randint(0, 101, size=28)  # Temperatures between 0 and 100
print(dt)


weekly_averages = np.mean(dt.reshape(4, 7), axis=1)


print(weekly_averages)


[27 23 42 49 60 43 59 29 79 13 55 84 18 62  3 26 87 22 60 89 29 32 69 89
 71 54 15 18]
[43.28571429 48.57142857 45.14285714 49.71428571]
