In [1]:
import numpy as np

In [3]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations? 

#ans.1 NumPy  is an open source Python library that has a wide range of inbuilt functions. 

#NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. 

#NumPy operations are implemented in C, making them significantly faster than equivalent operations in pure Python, especially for large datasets. 

#NumPy offers a wide range of mathematical functions that can be applied directly to arrays, simplifying complex operations.

#NumPy enables vectorized operations, which eliminate the need for explicit loops and thus improve both readability and performance.

#NumPy offers powerful indexing options that allow for more flexible and efficient data manipulation compared to native Python lists. 

In [5]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

#np.mean() 
#Computes the arithmetic mean of the elements along a specified axis
#use case
#When you want a simple arithmetic mean of the data without any weighting.
#When performance is a priority and you don’t need the added complexity of weights.

#np.average()
#Computes the weighted average of elements. If no weights are provided, it behaves similarly to np.mean().
##use case
#When you need to compute a weighted average, where some elements contribute more to the average than others.
#When you want the option to return additional information, like the sum of weights. 


data = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(data)  # Simple mean
average_value = np.average(data, weights=[1, 1, 1, 2, 2])  # Weighted average

print( mean_value)  # Output: 3.0
print( average_value)  # Output: 3.428


3.0
3.4285714285714284


In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

#Reversing a 1D Array

arr_1d = np.array([1, 2, 3, 4, 5])

reversed_arr_1d = arr_1d[::-1]

print( arr_1d)
print( reversed_arr_1d) 

#Reversing a 2D Array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along the first axis (rows)
reversed_rows = arr_2d[::-1, :]

# Reverse along the second axis (columns)
reversed_columns = arr_2d[:, ::-1]

print(arr_2d)
print(reversed_rows)
print(reversed_columns)



In [6]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
#data type of elements in an array can be determined using the .dtype attribute. 

arr = np.array([1, 2, 3, 4])

data_type = arr.dtype

print(data_type) 

#Understanding and selecting appropriate data types in NumPy is vital for optimizing memory usage and computational performance. By leveraging the .dtype attribute, we can easily check the data type of our arrays and make informed decisions about how to manage and manipulate our data effectively.


int64


In [7]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
#ndarray, or n-dimensional array,is a powerful, flexible, and efficient way to store and manipulate large datasets in multiple dimensions.
#ndarrays are stored in contiguous blocks of memory, which enhances performance, especially for mathematical operations and data processing.
#ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), making them suitable for representing vectors, matrices, and higher-dimensional datasets.


 
#ndarrays: Homogeneous; all elements must be of the same type.
 #Python Lists: Heterogeneous; can contain elements of different types (e.g., integers, strings, objects).

#ndarrays: Generally faster for numerical operations due to optimized C-based implementations and contiguous memory storage.
#Python Lists: Slower for numerical computations, as operations often require explicit looping.


#ndarrays: Advanced slicing and indexing capabilities, including multi-dimensional slicing and boolean indexing.
#Python Lists: Supports basic slicing but lacks the same level of flexibility and functionality.


SyntaxError: invalid syntax (3819507807.py, line 2)

In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

#1. Contiguous Memory Allocation
#NumPy Arrays: NumPy arrays are stored in contiguous blocks of memory, which improves cache locality. This means that when an operation accesses one element of the array, it is likely to access nearby elements as well, reducing the time taken to fetch data from memory.
#Python Lists: Python lists store references to objects, which can lead to non-contiguous memory allocation. This results in more cache misses and slower access times during operations.
#2. Homogeneous Data Types
#NumPy Arrays: All elements in a NumPy array are of the same type, which allows for optimized storage and faster computation. The fixed data type enables NumPy to use more efficient operations that take advantage of lower-level optimizations.
#Python Lists: Lists can store mixed data types, leading to additional overhead for type checking and potentially less efficient memory usage.
#3. Vectorized Operations
#NumPy Arrays: NumPy supports vectorized operations, which allow for operations on entire arrays without the need for explicit loops. This is implemented in C and optimized for performance, making operations significantly faster.
#Python Lists: Performing element-wise operations on lists typically requires using loops or list comprehensions, which are slower because they are executed in Python’s interpreted environment.
#4. Broadcasting
#NumPy Arrays: Broadcasting enables NumPy to perform operations on arrays of different shapes without the need for explicit replication of data. This feature allows for more concise and efficient code, as well as faster computations.
#Python Lists: Lists do not support broadcasting, requiring manual handling of shapes, which can lead to more complex and slower code.
#5. Built-in Functions
#NumPy Arrays: NumPy provides a rich set of optimized mathematical functions that can operate on arrays. These functions are implemented in C and often leverage multi-threading, making them faster than equivalent operations performed in Python.
#Python Lists: While lists can use built-in functions, these are typically not optimized for performance and lack the extensive numerical capabilities of NumPy.
#6. Reduced Overhead
#NumPy Arrays: The overhead associated with NumPy arrays is minimal compared to Python lists. Operations are performed in bulk rather than element by element, which reduces function call overhead and improves execution speed.
#Python Lists: Each operation on a list may incur additional overhead due to the need for dynamic memory management and type handling.

In [8]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively 


array1 = np.array([[11, 16, 31],
                   [44,34 , 26]])

array2 = np.array([[17, 81, 42],
                   [10, 22, 12]])

result_vstack = np.vstack((array1, array2))

print(array1)
print(array2)
print( result_vstack)     #vstack() combines arrays by stacking them vertically, resulting in more rows.


result_hstack = np.hstack((array1, array2))

print(result_hstack)      #hstack() combines arrays by stacking them horizontally, resulting in more columns.



[[11 16 31]
 [44 34 26]]
[[17 81 42]
 [10 22 12]]
[[11 16 31]
 [44 34 26]
 [17 81 42]
 [10 22 12]]
[[11 16 31 17 81 42]
 [44 34 26 10 22 12]]


In [9]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#fliplr() flips arrays left to right (horizontally).
#flipud() flips arrays up to down (vertically). 

#Both functions can be used on 2D arrays and can also be applied to higher-dimensional arrays where they affect the corresponding axes. 
# For 1D arrays, they behave similarly as there's no distinction between rows and columns.


array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flip the array left to right
flipped_lr = np.fliplr(array_2d)

print(array_2d)
print(flipped_lr)

# Flip the array up to down
flipped_ud = np.flipud(array_2d)

print( flipped_ud) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [10]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits? 

#The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. 

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array into 3 parts
split_3 = np.array_split(array_1d, 3)
print(split_3)

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Split the 2D array into 2 parts
split_2d = np.array_split(array_2d, 2)
for part in split_2d:
    print(part)  


    # Split the 1D array into 4 parts
uneven_split = np.array_split(array_1d, 4)
print(uneven_split)    #the 1D array [1, 2, 3, 4, 5, 6, 7, 8, 9] is split into 4 parts>>>>> the first bpart contain 3 element and 2 and 3 rd and 4 th part contain 2 element each 



[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [11]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?



#Vectorization refers to the ability to perform operations on entire arrays or large chunks of data simultaneously, rather than element by element through explicit loops.
# This is achieved by using NumPy's built-in functions

arr = np.arange(1, 100)

# Vectorized operation: Squaring each element
squared = arr ** 2  


#Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes. 
#Instead of requiring arrays to be the same shape, NumPy automatically expands the smaller array to match the shape of the larger one during the operation. 


A = np.array([[4, 8, 5],
              [1, 4, 12]])

B = np.array([10, 20, 30])

# Broadcasting: Add B to each row of A
result = A + B

print( result)



[[14 28 35]
 [11 24 42]]
